### ISSUE TITLE
Installation "Hängt"

### ISSUE THREAD

**Issue by LxSTx** [DaBurnerGermany/DaPublicServices#1]
`
Uncaught SyntaxError: Unexpected token < in JSON at position 0 (install.php:1)
    at JSON.parse (<anonymous>)
    at Object.success (main.js:436:29)
    at c (jquery.js:1096:41)
    at Object.fireWith [as resolveWith] (jquery.js:1133:81)
    at l (jquery.js:2944:403)
    at XMLHttpRequest.<anonymous> (jquery.js:3035:217)
`
Server Configuration > Database create > Create Entire Database
"medic" & "police" db wird erstellt, danach passiert allerdings nichts mehr

**Comment by DaBurnerGermany** [comment]
seems that i fucked up in the intaller and the mysql dump. I'll fix this asap.

**Comment by LxSTx** [comment]
> seems that i fucked up in the intaller and the mysql dump. I'll fix this asap.

No problem, if you need some help hit me up

**Comment by alphawarriord** [comment]
Is there any solution i would realy like to use this project :)

**Comment by LxSTx** [comment]
> 

as long as he is not fixing the installer and/or the sql dump, you could try to rebuild the db yourself

**Comment by DaBurnerGermany** [comment]
> Installer should work now. Can you retry?

**Comment by DaBurnerGermany** [comment]
> Is there any solution i would realy like to use this project :)

Should work now

**Comment by LxSTx** [comment]
> 

imma try it real quick

**Comment by DaBurnerGermany** [comment]
> 

Thanks, if it works then it should really work.

**Comment by LxSTx** [comment]
okok, i was settin up everything. Locally i had no problems but if someone wanna set it up on an hosted web server with Plesk(without "full" access) you should add "ROW_FORMAT=DYNAMIC" to every table then everything will work fine

**Comment by DaBurnerGermany** [comment]
@LxSTx i think you can set it via my.ini
