### ISSUE TITLE
Funktioniert leider nicht

### ISSUE THREAD

**Issue by Gogadon** [DaBurnerGermany/DaPublicServices#2]
Hey ich wollte mal anmerken das es leider nicht auf "mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))" funktioniert!
Könnte man das fixxen würde mich freuen =D

**Comment by DaBurnerGermany** [comment]
Kann ich mir angucken, hast du irgendwelche Fehler ?

**Comment by Gogadon** [comment]
ne fehler selber nicht wirklich nur funktionieren manche sachen nicht z.B. Polizei Dashboard geht nicht!

**Comment by DaBurnerGermany** [comment]
Wenn du F12 im Browser öffnest und dann auf Netzwerkanalyse gehst müsste dort einmal der datasetloader stehen, steht da in antwort was drin?

**Comment by Gogadon** [comment]
Kann ich heute nicht mehr ausprobieren ich muss morgen früh raus =D

**Comment by DaBurnerGermany** [comment]
Kannst ja die Tage mal schauen
