### ISSUE TITLE
Vorschlag

### ISSUE THREAD

**Issue by Gogadon** [DaBurnerGermany/DaPublicServices#3]
Es wäre schön wenn bei den Ausbildungen bei Ausbilder nicht die UserID stehen würde sondern der User Name oder die Dienstnummer z.B. =D

![grafik](https://user-images.githubusercontent.com/58675646/187030128-3423aaac-9787-4a27-9e64-51a5dbdd1ea7.png)

**Comment by DaBurnerGermany** [comment]
Ups, wird erledigt

**Comment by DaBurnerGermany** [comment]
Mit dem Update von heute behoben.
Bitte einmal Sourcen ziehen und dann public_services/install/update/update.php ausführen, dann sollte das erledigt sein.
